# Generated by Django 6.0 on 2025-12-05 21:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('dataInscricao', models.DateTimeField(blank=True, null=True)),
                ('dataInscricaoFinal', models.DateTimeField(blank=True, null=True)),
                ('dataEventoInicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataEventoFinal', models.DateTimeField()),
                ('local', models.CharField(max_length=200)),
                ('contatos', models.JSONField(blank=True, default=list)),
                ('categoria', models.ManyToManyField(related_name='eventos', to='my_app.categoria')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-dataEventoInicio'],
            },
        ),
    ]
