# Generated by Django 6.0 on 2025-12-19 11:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['email'],
            },
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icone',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='event',
            name='contatos',
        ),
        migrations.AlterField(
            model_name='event',
            name='dataEventoInicio',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='contatos',
            field=models.ManyToManyField(related_name='contatos', to='my_app.contato'),
        ),
    ]
