# Generated by Django 6.0 on 2025-12-21 02:29

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_contato_remove_categoria_icone_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=my_app.models.Event.evento_upload_path),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
